# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: playTradingCiCd

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_bump
      uses: anothrNick/github-tag-action@1.56.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        INITIAL_VERSION: 1.0.3
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{steps.tag_bump.outputs.new_tag}}    
        
  build-and-deploy-service:
    runs-on: ubuntu-latest
    needs: generate-version
    env:
      ACR_NAME: playeconomyazurecontainerregistry
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image      
      uses: docker/build-push-action@v2.9.0
      with:        
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT=${{secrets.NUGET_READ_PAT}}"
        tags: ${{env.ACR_NAME}}.azurecr.io/play.trading:${{needs.generate-version.outputs.new_version}}
